"""``klm scaffold`` — the repository furniture around a KiCad project.

Workflows, ignore rules, attributes, project config and a README. None of it is
clever; all of it is the stuff nobody writes by hand twice, and getting one line
of `.gitattributes` wrong produces a whole-file diff on every commit.

Every generated file carries a managed block:

    # Generated by klm scaffold 0.1.0 — edits outside the markers are preserved.
    # --- klm:managed ---
    ...
    # --- klm:end ---

`--check` compares what is inside the markers against what this klm would write;
`--update` replaces only that region. Everything a user adds above or below
survives, which is what makes regeneration something they will actually run
rather than something they avoid because it eats their edits.

The pinned versions in the workflows are deliberate. An unpinned
`kicad/kicad:latest` means the same commit produces different gerbers next
month, and reproducibility that depends on nobody upgrading upstream is not
reproducibility (docs/15 §7).
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

from klm import __version__

__all__ = [
    "KICAD_IMAGE",
    "PRESETS",
    "ScaffoldPlan",
    "apply_scaffold",
    "plan_scaffold",
]

#: Pinned exactly. `-full` carries KiCad's standard symbol and footprint
#: libraries, which clean-room verification needs: a project may legitimately
#: reference `power:GND`, and those ship with KiCad rather than with the repo
#: (docs/14 Q11).
KICAD_IMAGE = "kicad/kicad:9.0.9-full"

BEGIN = "# --- klm:managed ---"
END = "# --- klm:end ---"

PRESETS = {
    "publish": ("verify", "artifacts", "release", "gitignore", "gitattributes", "klm.toml",
                "readme", "pre-commit"),
    "private": ("verify", "gitignore", "gitattributes", "klm.toml", "pre-commit"),
}


def _header(comment: str = "#") -> str:
    return (
        f"{comment} Generated by klm scaffold {__version__} — "
        f"edits outside the markers are preserved.\n"
        f"{comment} Regenerate: klm scaffold --update\n"
    )


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------


def _verify_workflow(project_name: str) -> str:
    return f"""name: verify

on:
  pull_request:
  push:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest
    container:
      image: {KICAD_IMAGE}
      # The official KiCad image ends with `USER kicad`, and a container job's
      # workspace is created by the runner as root — so actions/checkout fails
      # on permissions before anything else runs. See docs/14 Q11.
      options: --user root
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install klm
        # Pinned so the same commit verifies the same way next month. This is
        # the klm that generated the workflow; change it deliberately, and make
        # sure the version is published before the first run.
        run: pip install --break-system-packages klm=={__version__}

      - name: Clean-room verification
        run: klm verify --clean-room --format github

      - name: Preflight
        run: klm fab --check --format github

      - name: Cost and BOM regression
        # Only if the project committed a baseline. Without a catalog here the
        # comparison is the BOM half alone, which is the half that runs on a
        # stranger's machine — a priced baseline says so and fails rather than
        # quietly passing. Record one with `klm cost baseline`.
        run: |
          if [ -f .klm/cost-baseline.json ]; then
            klm cost check --format github
          else
            echo "no .klm/cost-baseline.json; skipping"
          fi
"""


def _artifacts_workflow(project_name: str, variants: tuple[str, ...]) -> str:
    matrix = ", ".join(variants) if variants else "default"
    variant_flag = (
        "--variant ${{ matrix.variant }}" if variants else ""
    )
    suffix = "-${{ matrix.variant }}" if variants else ""
    return f"""name: artifacts

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: {KICAD_IMAGE}
      options: --user root
    strategy:
      matrix:
        variant: [{matrix}]
    steps:
      - uses: actions/checkout@v4
      - run: pip install --break-system-packages klm=={__version__}

      - name: Fabrication package
        run: klm fab {variant_flag} --output artifacts/fab --normalize-timestamps

      - name: Documentation
        # xvfb-run defensively: whether any kicad-cli export path still needs an
        # X server on this version is unverified, and it costs nothing if not.
        run: xvfb-run -a klm docs --all --output artifacts/docs

      - uses: actions/upload-artifact@v4
        with:
          name: {project_name}{suffix}
          path: artifacts/

      - name: Job summary
        run: klm report --format github-summary >> "$GITHUB_STEP_SUMMARY"
"""


def _release_workflow(project_name: str) -> str:
    return f"""name: release

on:
  push:
    tags: ["v*"]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: {KICAD_IMAGE}
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - run: pip install --break-system-packages klm=={__version__}

      - name: Verify before releasing
        run: klm verify --clean-room

      - name: Build everything
        run: |
          klm fab --output artifacts/fab --normalize-timestamps
          xvfb-run -a klm docs --all --output artifacts/docs

      - name: Attach to the release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**
"""


_GITIGNORE = """# KiCad backups and autosaves
*-backups/
*.kicad_prl
*.kicad_sch-bak
*.kicad_pcb-bak
_autosave-*
*.000
*.bak

# Machine-local caches. `fp-info-cache` is a footprint index that differs per
# machine, and `.kicad_prl` holds which sheets you had open — both produce a
# diff on every session and conflicts that mean nothing.
fp-info-cache
*.lck

# Build output
/fab/
/artifacts/
.klm-fab/
.klm-vendor/
*.klm-bak
"""

_GITATTRIBUTES = """# CRLF in a .kicad_pcb produces a whole-file diff and confuses tooling.
# Forcing LF is the single highest-value line in this file.
* text=auto eol=lf
*.kicad_sch  text eol=lf
*.kicad_pcb  text eol=lf
*.kicad_sym  text eol=lf
*.kicad_mod  text eol=lf
*.kicad_pro  text eol=lf
*.step       text eol=lf
*.pdf        binary
*.png        binary
*.zip        binary
"""

_PRE_COMMIT = """repos:
  - repo: local
    hooks:
      - id: klm-verify
        name: klm clean-room verification
        entry: klm verify --clean-room
        language: system
        pass_filenames: false
        files: \\.(kicad_sch|kicad_pcb|kicad_sym|kicad_mod)$
"""


def _klm_toml(project_name: str) -> str:
    return f"""[project]
name = "{project_name}"
revision = "rev-a"

[verify]
require_3d_models = false
require_fields = ["MPN", "Manufacturer"]

[fab]
profile = "jlcpcb"
normalize_timestamps = true

[artifacts]
schematic_pdf = true
board_render = true
step_export = true

# Build configurations. `dnp` lists references left unpopulated; `overrides`
# replaces a Value for this variant only.
# [variants.basic]
# dnp = ["U5", "J3"]
"""


def _readme(project_name: str) -> str:
    return f"""# {project_name}

## Opening this project

Clone and open `{project_name}.kicad_pro` in KiCad. All symbols, footprints and
libraries are contained in this repository — no external library setup is required.

That claim is enforced on every push by `klm verify --clean-room`, which resolves
the project on a machine with no catalog and no configuration. A README that
asserts something CI proves is worth more than one that asserts something nobody
checks.

## Downloads

The most recent `main` build publishes a schematic PDF, a BOM and a fabrication
package as workflow artifacts.

## Building

| Variant | Description |
|---|---|
| (default) | Everything populated |
"""


# ---------------------------------------------------------------------------
# Planning and writing
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Template:
    key: str
    path: str
    body: str
    comment: str = "#"
    managed: bool = True
    """False for files a user is expected to rewrite wholesale, like the README."""


def templates(project_name: str, variants: tuple[str, ...]) -> dict[str, Template]:
    return {
        t.key: t
        for t in (
            Template("verify", ".github/workflows/verify.yml", _verify_workflow(project_name)),
            Template(
                "artifacts",
                ".github/workflows/artifacts.yml",
                _artifacts_workflow(project_name, variants),
            ),
            Template("release", ".github/workflows/release.yml", _release_workflow(project_name)),
            Template("gitignore", ".gitignore", _GITIGNORE),
            Template("gitattributes", ".gitattributes", _GITATTRIBUTES),
            Template("pre-commit", ".pre-commit-config.yaml", _PRE_COMMIT),
            Template("klm.toml", "klm.toml", _klm_toml(project_name)),
            Template("readme", "README.md", _readme(project_name), comment="<!--", managed=False),
        )
    }


@dataclass
class Change:
    path: str
    action: str
    """`create`, `update` or `unchanged`."""


@dataclass
class ScaffoldPlan:
    root: Path
    preset: str
    changes: list[Change] = field(default_factory=list)
    contents: dict[str, str] = field(default_factory=dict)

    @property
    def needed(self) -> list[Change]:
        return [c for c in self.changes if c.action != "unchanged"]

    @property
    def drifted(self) -> bool:
        return bool(self.needed)


def plan_scaffold(
    root: Path,
    *,
    preset: str = "publish",
    project_name: str | None = None,
    variants: tuple[str, ...] = (),
) -> ScaffoldPlan:
    """Work out what scaffolding would write, without writing anything."""
    if preset not in PRESETS:
        raise KeyError(f"no preset {preset!r} (known: {', '.join(sorted(PRESETS))})")

    name = project_name or _guess_name(root)
    plan = ScaffoldPlan(root=root, preset=preset)
    available = templates(name, variants)

    for key in PRESETS[preset]:
        template = available[key]
        target = root / template.path
        wanted = _render(template)
        plan.contents[template.path] = wanted

        if not target.exists():
            plan.changes.append(Change(template.path, "create"))
            continue
        current = target.read_text(encoding="utf-8")
        if not template.managed:
            # A README is the user's document; scaffold writes one if missing
            # and never touches it again.
            plan.changes.append(Change(template.path, "unchanged"))
            plan.contents[template.path] = current
            continue
        merged = _merge(current, wanted)
        plan.contents[template.path] = merged
        plan.changes.append(
            Change(template.path, "unchanged" if merged == current else "update")
        )

    return plan


def apply_scaffold(plan: ScaffoldPlan) -> list[Change]:
    """Write the plan. Returns only what actually changed."""
    written: list[Change] = []
    for change in plan.needed:
        target = plan.root / change.path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(plan.contents[change.path], encoding="utf-8", newline="\n")
        written.append(change)
    return written


def _guess_name(root: Path) -> str:
    projects = sorted(root.glob("*.kicad_pro"))
    return projects[0].stem if projects else root.name


def _render(template: Template) -> str:
    if not template.managed:
        return template.body
    return f"{_header()}{BEGIN}\n{template.body}{END}\n"


_BLOCK = re.compile(
    rf"^{re.escape(BEGIN)}$.*?^{re.escape(END)}$", re.MULTILINE | re.DOTALL
)


def _merge(current: str, wanted: str) -> str:
    """Replace the managed block in ``current`` with the one from ``wanted``.

    A file with no markers at all is left alone apart from having the block
    appended — someone wrote it by hand before scaffold existed, and silently
    replacing it would be exactly the behaviour that makes people stop running
    the command.
    """
    match = _BLOCK.search(wanted)
    if match is None:  # pragma: no cover - every managed template has a block
        return current
    block = match.group(0)

    if _BLOCK.search(current) is None:
        separator = "" if current.endswith("\n") or not current else "\n"
        return f"{current}{separator}{_header()}{block}\n"
    return _BLOCK.sub(lambda _: block, current, count=1)
