; Inno Setup script for the klm Windows installer.
;
;   iscc /DKlmVersion=0.1.0 packaging\klm.iss
;
; Produces  dist\installer\klm-setup-<version>.exe  from  dist\klm\  (the
; PyInstaller output).  Build that first; this script only packages it.
;
; Inno Setup rather than WiX/MSI: this is a single-user desktop tool, and the
; things MSI is better at — Group Policy deployment, administrative installs,
; per-machine repair — are things nobody will do to it.  Inno gives the
; next-next-next wizard with a fraction of the ceremony.
;
; Installs per-user by default (PrivilegesRequiredOverridesAllowed=dialog lets
; the user choose).  A per-user install needs no administrator, which matters:
; the alternative is a UAC prompt for a program that only ever writes to the
; user's own catalog and projects.

#ifndef KlmVersion
  #define KlmVersion "0.0.0"
#endif

#define KlmName "klm"
#define KlmFullName "klm — KiCad Library Manager"
#define KlmPublisher "Roland Sobczak"
#define KlmUrl "https://github.com/RolandSobczak/klm"

[Setup]
AppId={{7E2A9C34-8F41-4B6D-9C2E-5A1D3F80B7C6}
AppName={#KlmFullName}
AppVersion={#KlmVersion}
AppPublisher={#KlmPublisher}
AppPublisherURL={#KlmUrl}
AppSupportURL={#KlmUrl}/issues
DefaultDirName={autopf}\klm
DefaultGroupName=klm
DisableProgramGroupPage=yes
; The licence and a one-screen "what this is" page, then the usual wizard.
LicenseFile=..\LICENSE
OutputDir=..\dist\installer
OutputBaseFilename=klm-setup-{#KlmVersion}
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
; 64-bit only.  A 32-bit KiCad has not shipped for years and building a second
; architecture to serve nobody is not free.
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
UninstallDisplayIcon={app}\klm-app.exe
; Generated by `packaging/make_icons.py` from the one source image, so it is not
; in the repository. Guarded rather than assumed: a checkout without the icon
; should build an installer with the default one, not fail to compile.
#if FileExists(AddBackslash(SourcePath) + "klm.ico")
SetupIconFile=klm.ico
#endif
; Tells Windows to re-read the environment when PATH changes, so a terminal
; opened after installing finds `klm` without a reboot.
ChangesEnvironment=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "polish"; MessagesFile: "compiler:Languages\Polish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"
Name: "addtopath"; Description: "Add the klm command to PATH"; \
    GroupDescription: "Command line"; \
    Flags: checkedonce

[Files]
; The whole PyInstaller directory, verbatim.  `recursesubdirs` matters: the UI
; and the FreeCAD script both live in subdirectories and a flat copy would
; produce an app that starts and then serves nothing.
Source: "..\dist\klm\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\klm"; Filename: "{app}\klm-app.exe"
Name: "{group}\Uninstall klm"; Filename: "{uninstallexe}"
Name: "{autodesktop}\klm"; Filename: "{app}\klm-app.exe"; Tasks: desktopicon

[Registry]
; PATH, appended rather than replaced, and only when it is not already there —
; running the installer twice must not leave two copies of the same directory.
; The key differs between a per-user and a per-machine install, so there are two
; entries with opposite checks rather than one clever one.
Root: HKCU; Subkey: "Environment"; ValueType: expandsz; ValueName: "Path"; \
    ValueData: "{olddata};{app}"; \
    Tasks: addtopath; Check: not IsAdminInstallMode and NeedsAddPath(ExpandConstant('{app}'))
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; \
    ValueType: expandsz; ValueName: "Path"; ValueData: "{olddata};{app}"; \
    Tasks: addtopath; Check: IsAdminInstallMode and NeedsAddPath(ExpandConstant('{app}'))

[Run]
Filename: "{app}\klm-app.exe"; Description: "{cm:LaunchProgram,klm}"; \
    Flags: nowait postinstall skipifsilent

[Code]
{ ---------------------------------------------------------------------------
  PATH
  --------------------------------------------------------------------------- }

function NeedsAddPath(Dir: String): Boolean;
var
  Existing: String;
  RootKey: Integer;
  SubKey: String;
begin
  if IsAdminInstallMode() then
  begin
    RootKey := HKEY_LOCAL_MACHINE;
    SubKey := 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment';
  end
  else
  begin
    RootKey := HKEY_CURRENT_USER;
    SubKey := 'Environment';
  end;

  if not RegQueryStringValue(RootKey, SubKey, 'Path', Existing) then
  begin
    Result := True;
    exit;
  end;
  { Semicolons on both sides so `C:\klm` does not match `C:\klm-old`. }
  Result := Pos(';' + Uppercase(Dir) + ';', ';' + Uppercase(Existing) + ';') = 0;
end;

procedure RemoveFromPath(Dir: String);
var
  Existing: String;
  RootKey: Integer;
  SubKey: String;
  Index: Integer;
begin
  if IsAdminInstallMode() then
  begin
    RootKey := HKEY_LOCAL_MACHINE;
    SubKey := 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment';
  end
  else
  begin
    RootKey := HKEY_CURRENT_USER;
    SubKey := 'Environment';
  end;

  if not RegQueryStringValue(RootKey, SubKey, 'Path', Existing) then
    exit;

  Index := Pos(';' + Uppercase(Dir), ';' + Uppercase(Existing));
  if Index = 0 then
    exit;
  Delete(Existing, Index, Length(Dir) + 1);
  RegWriteExpandStringValue(RootKey, SubKey, 'Path', Existing);
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  { Uninstalling must leave PATH as it found it. A stale entry pointing at a
    deleted directory is harmless but untidy, and it accumulates. }
  if CurUninstallStep = usPostUninstall then
    RemoveFromPath(ExpandConstant('{app}'));
end;

{ ---------------------------------------------------------------------------
  WebView2

  pywebview's Windows backend renders through Microsoft's WebView2 runtime.  It
  ships with Windows 11 and with updated Windows 10, but not with every machine,
  and its absence is the one failure that would make a successfully installed
  klm open a blank window.  So it is checked here and the user is offered the
  official bootstrapper rather than being left to read a stack trace.

  klm's own rule is that absence degrades rather than fails: without WebView2
  `klm app` already falls back to `klm serve` and a browser URL, so this is a
  better experience, not a prerequisite.  The install is never blocked on it.
  --------------------------------------------------------------------------- }

const
  WebView2Key =
    'SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\' +
    '{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}';
  WebView2UserKey =
    'SOFTWARE\Microsoft\EdgeUpdate\Clients\' +
    '{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}';
  WebView2Url = 'https://go.microsoft.com/fwlink/p/?LinkId=2124703';

function WebView2Installed(): Boolean;
var
  Version: String;
begin
  Result :=
    (RegQueryStringValue(HKLM, WebView2Key, 'pv', Version) and (Version <> '') and
     (Version <> '0.0.0.0')) or
    (RegQueryStringValue(HKCU, WebView2UserKey, 'pv', Version) and (Version <> '') and
     (Version <> '0.0.0.0'));
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  ErrorCode: Integer;
begin
  if (CurStep = ssPostInstall) and (not WebView2Installed()) then
  begin
    if MsgBox(
      'klm draws its window with the Microsoft WebView2 runtime, which this ' +
      'machine does not have.' + #13#10#13#10 +
      'klm is installed and will still work without it — it opens in your ' +
      'browser instead. Download WebView2 now for the native window?',
      mbConfirmation, MB_YESNO) = IDYES then
    begin
      ShellExec('open', WebView2Url, '', '', SW_SHOW, ewNoWait, ErrorCode);
    end;
  end;
end;
